name: Security Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master

  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/Dockerfile
  
  tffmt:
    name: Terraform Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        id: fmt
        working-directory: infrastructure
        run: terraform fmt -check
      - name: Terraform init
        id: init
        working-directory: infrastructure
        run: terraform init -backend=false
      - name: Terraform Validate
        id: validate
        working-directory: infrastructure
        run: terraform validate -no-color
      - name: Terraform Test
        id: test
        working-directory: infrastructure
        run: terraform test -no-color
