name: Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infrastructure/
          quiet: true
          framework: terraform

  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: docker/Dockerfile